version: '3.9'

services:
  keycloak:
    build: .
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_DEFAULT_THEME: lifelike
    volumes:
      - ./theme:/opt/jboss/keycloak/themes/lifelike
      - ./disable-cache.cli:/opt/jboss/startup-scripts/disable-cache.cli
    ports:
      - 8080:8080
